## Importing requirements

In [5]:
import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Make Hazy Data

In [2]:
def get_file_name(path):
    basename = os.path.basename(path)
    onlyname = os.path.splitext(basename)[0]
    return onlyname

def gen_haze(img, depth_img):
    
    depth_img_3c = np.zeros_like(img)
    depth_img_3c[:,:,0] = depth_img
    depth_img_3c[:,:,1] = depth_img
    depth_img_3c[:,:,2] = depth_img

    beta = random.randint(100,150)/100
    norm_depth_img = depth_img_3c/255
    trans = np.exp(-norm_depth_img*beta)

    A = 255
    hazy = img*trans + A*(1-trans)
    hazy = np.array(hazy, dtype=np.uint8)
    
    return hazy

In [49]:
import os
filename_cycle=[]
for filename in os.listdir("C:/Hazing/Haze_dataset/Camel_dataset/Person/Visual_Person"):
    if filename.endswith(".jpg"):
        filename_cycle.append(filename)

In [50]:
len(filename_cycle)

1488

In [ ]:
import numpy as np

In [22]:
for i in range(0,len(filename_cycle)):
     pl=filename_cycle[i].split(".jpg")
     #     parray=np.asarray(filename_cycle[i])
     print(str(pl[0]))

1
2


In [33]:
pwd

'C:\\Hazing\\haze-synthesis'

In [53]:
for i in range(0,len(filename_cycle)):
        pl=filename_cycle[i].split(".jpg")
        fname =str(pl[0])
        path = f"Root_person/{fname}.jpg"

        print(fname)

        img = plt.imread(path)

        depth_path = f"Root_person/{fname}_disp.jpeg"
        depth_img = plt.imread(depth_path)

        depth_img_3c = np.zeros_like(img)
        depth_img_3c[:,:,0] = depth_img
        depth_img_3c[:,:,1] = depth_img
        depth_img_3c[:,:,2] = depth_img

        beta=1.5
        norm_depth_img = depth_img_3c/255
        trans = np.exp(-norm_depth_img*beta)

        beta2=3.5
        trans2 = np.exp(-norm_depth_img*beta2)

        A = 255
        hazy = img*trans + A*(1-trans)
        hazy = np.array(hazy, dtype=np.uint8)

        hazy2 = img*trans2 + A*(1-trans2)
        hazy2 = np.array(hazy2, dtype=np.uint8)
        cv2.imwrite("Hazed_data/Person/Light_haze/"+fname+".jpg",hazy)
        cv2.imwrite("Hazed_data/Person/Dense_haze/"+fname+".jpg",hazy2)
# plt.figure(figsize=(16,18))
# plt.subplot(321), plt.imshow(img)
# plt.subplot(322), plt.imshow(depth_img, cmap="gray")
# plt.subplot(323), plt.imshow(trans, cmap="gray")
# plt.subplot(324), plt.imshow(hazy)
# plt.subplot(325), plt.imshow(trans2, cmap="gray")
# plt.subplot(326), plt.imshow(hazy2)
# plt.show()

000001
000002
000003
000004
000005
000006
000007
000008
000009
000010
000011
000012
000013
000014
000015
000016
000017
000018
000019
000020
000021
000022
000023
000024
000025
000026
000027
000028
000029
000030
000031
000032
000033
000034
000035
000036
000037
000038
000039
000040
000041
000042
000043
000044
000045
000046
000047
000048
000049
000050
000051
000052
000053
000054
000055
000056
000057
000058
000059
000060
000061
000062
000063
000064
000065
000066
000067
000068
000069
000070
000071
000072
000073
000074
000075
000076
000077
000078
000079
000080
000081
000082
000083
000084
000085
000086
000087
000088
000089
000090
000091
000092
000093
000094
000095
000096
000097
000098
000099
000100
000101
000102
000103
000104
000105
000106
000107
000108
000109
000110
000111
000112
000113
000114
000115
000116
000117
000118
000119
000120
000121
000122
000123
000124
000125
000126
000127
000128
000129
000130
000131
000132
000133
000134
000135
000136
000137
000138
000139
000140
000141
000142
000143

In [ ]:
# cv2.imwrite(f"{fname}_syn.jpg", cv2.cvtColor(hazy2, cv2.COLOR_BGR2RGB))

In [3]:
#%cd C:\Hazing\haze-synthesis\PICS\Trackers_Output\Sort+Yv7\Car

## Ground truth processing for customized dataset

In [70]:
%cd Person

C:\Hazing\haze-synthesis\Hazed_data\Person


In [66]:
# import pandas as pd
# df=pd.read_csv('Seq1-Vis_car.txt',sep="	")

In [230]:
dfgt=df.to_numpy().tolist()

In [231]:
len(df)

2393

In [2]:
import pandas as pd

In [229]:
df=pd.read_csv('Seq1-Vis_person.txt',
              sep='\t',
              names=["Frame_no", "ID", "no_of_IDs","X","Y","W","H"])

In [241]:
# id no. 2 in car dataset
# id no. 1 in person dataset
# id no. 1 in cycle dataset

In [214]:
Usableframes_list_person=[]
for i in range(0,len(dfgt)):
    if dfgt[i][1]==1:
        Usableframes_list_person.append(str(int(dfgt[i][0]))+".jpg")

In [215]:
Usableframes_list_allcols=[]
for i in range(0,len(dfgt)):
    if dfgt[i][1]==1:
        Usableframes_list_allcols.append(str(int(dfgt[i][0]))+"  "+str(int(dfgt[i][3]))+"  "+str(int(dfgt[i][4]))+"  "+str(int(dfgt[i][5]))+"  "+str(int(dfgt[i][6])))

In [217]:
Usableframes_list_allcols

['58  0  96  20  36',
 '59  0  96  25  36',
 '60  0  96  27  61',
 '61  0  96  31  61',
 '62  0  96  34  61',
 '63  0  96  37  61',
 '64  0  97  37  61',
 '65  2  97  39  61',
 '66  5  97  41  61',
 '67  8  97  41  61',
 '68  11  97  40  61',
 '69  14  97  40  61',
 '70  18  97  40  61',
 '71  21  97  39  61',
 '72  24  97  39  61',
 '73  28  97  39  61',
 '74  31  97  39  61',
 '75  34  97  38  60',
 '76  38  97  38  60',
 '77  41  98  38  60',
 '78  44  98  38  60',
 '79  47  98  38  60',
 '80  50  98  38  60',
 '81  54  98  38  60',
 '82  57  98  38  60',
 '83  60  98  38  60',
 '84  63  98  38  60',
 '85  66  98  38  60',
 '86  70  99  38  60',
 '87  73  99  38  60',
 '88  76  99  38  60',
 '89  79  99  38  60',
 '90  83  99  38  60',
 '91  86  99  37  60',
 '92  89  98  37  60',
 '93  92  98  37  60',
 '94  95  98  37  60',
 '95  99  98  37  60',
 '96  102  98  37  60',
 '97  105  98  37  60',
 '98  108  98  36  60',
 '99  112  98  36  60',
 '100  115  98  36  60',
 '101  118  98 

In [218]:
df_lstusableallcols = pd.DataFrame(Usableframes_list_allcols)

In [219]:
df_lstusableallcols

0
0       58  0  96  20  36
1       59  0  96  25  36
2       60  0  96  27  61
3       61  0  96  31  61
4       62  0  96  34  61
..                    ...
102  160  310  97  25  61
103  161  313  97  23  61
104  162  316  97  20  61
105  163  320  97  15  61
106  164  323  97  12  61

[107 rows x 1 columns]

In [232]:
with open('Person_generated_under_haze_GT.txt', 'a') as f:
    for i in range(0,len(dfgt)):
        if dfgt[i][1]==1:
             f.write(str(dfgt[i][0])+"  "+str(dfgt[i][3])+"  "+str(dfgt[i][4])+"  "+str(dfgt[i][5])+"  "+str(dfgt[i][6])+ '\n')

In [226]:
dfgt

[[58.0, 1.0, 1.0, -0.43126, 96.797, 20.584, 36.973],
 [59.0, 1.0, 1.0, -0.43126, 96.797, 25.814, 36.973],
 [60.0, 1.0, 1.0, -0.43126, 96.797, 27.423, 61.916],
 [61.0, 1.0, 1.0, -0.43126, 96.797, 31.849, 61.916],
 [62.0, 1.0, 1.0, -0.43126, 96.797, 34.665, 61.916],
 [63.0, 1.0, 1.0, -0.43126, 96.797, 37.079, 61.916],
 [64.0, 1.0, 1.0, -0.43126, 97.199, 37.079, 61.514],
 [65.0, 1.0, 1.0, 2.3849, 97.199, 39.292, 61.514],
 [66.0, 1.0, 1.0, 5.2011, 97.199, 41.504, 61.514],
 [67.0, 1.0, 1.0, 8.4196, 97.3, 41.203, 61.514],
 [68.0, 1.0, 1.0, 11.638, 97.4, 40.901, 61.514],
 [69.0, 1.0, 1.0, 14.857, 97.501, 40.599, 61.514],
 [70.0, 1.0, 1.0, 18.075, 97.601, 40.297, 61.514],
 [71.0, 1.0, 1.0, 21.407, 97.653, 39.985, 61.41],
 [72.0, 1.0, 1.0, 24.738, 97.706, 39.673, 61.306],
 [73.0, 1.0, 1.0, 28.069, 97.758, 39.36, 61.202],
 [74.0, 1.0, 1.0, 31.401, 97.81, 39.048, 61.098],
 [75.0, 1.0, 1.0, 34.732, 97.862, 38.736, 60.993],
 [76.0, 1.0, 1.0, 38.064, 97.914, 38.423, 60.889],
 [77.0, 1.0, 1.0, 41.291

In [21]:
pwd

'E:\\Hazy_dataset'

In [19]:
df_lstusableallcols

0
0      1  16  103  69  52
1      2  19  105  69  53
2      3  22  106  70  53
3      4  25  107  70  54
4      5  27  108  70  54
5      6  30  110  71  55
6      7  33  111  72  56
7      8  36  113  73  57
8      9  39  115  74  57
9     10  41  116  74  58
10    11  44  118  75  59
11    12  47  120  76  60
12    13  50  121  77  61
13    14  53  123  78  61
14    15  55  124  79  62
15    16  58  126  80  63
16    17  61  128  81  64
17    18  64  129  81  64
18    19  67  131  83  65
19    20  71  133  84  67
20    21  74  135  85  68
21    22  78  137  87  69
22    23  81  139  88  70
23    24  85  141  89  71
24    25  88  143  90  72
25    26  92  145  92  73
26    27  95  147  93  74
27    28  99  149  94  75
28   29  102  151  96  76
29   30  106  153  97  77
30   31  110  155  99  79
31  32  114  158  101  81
32  33  118  160  104  83
33  34  122  162  106  84
34  35  126  165  108  86
35  36  130  167  110  88
36  37  136  170  112  85
37  38  139  172  115  86
38  39  145  175  118  86
39  40  150  178  119  82
40  41  155  181  120  78
41  42  161  184  121  75
42  43  166  187  122  71
43  44  171  190  123  67
44  45  177  193  124  63
45  46  182  196  125  60
46  47  189  200  122  56
47  48  195  204  120  52
48  49  201  208  118  49
49  50  208  212  115  45
50  51  214  216  113  41
51  52  221  219  111  38

In [10]:
dfgt

[[669.0, 1.0, 1.0, 323.67, 111.57, 13.043, 29.581],
 [670.0, 1.0, 1.0, 323.06, 111.53, 13.649, 29.581],
 [671.0, 1.0, 1.0, 322.46, 111.48, 14.255, 29.581],
 [672.0, 1.0, 1.0, 321.85, 111.43, 14.86, 29.581],
 [673.0, 1.0, 1.0, 321.25, 111.39, 15.466, 29.581],
 [674.0, 1.0, 1.0, 320.64, 111.34, 16.071, 29.581],
 [675.0, 1.0, 1.0, 320.35, 110.88, 15.373, 29.697],
 [676.0, 1.0, 1.0, 320.06, 110.41, 14.674, 29.813],
 [677.0, 1.0, 1.0, 319.77, 109.94, 13.975, 29.93],
 [678.0, 1.0, 1.0, 319.48, 109.48, 13.276, 30.046],
 [679.0, 1.0, 1.0, 318.5, 109.29, 13.509, 29.907],
 [680.0, 1.0, 1.0, 317.52, 109.1, 13.742, 29.767],
 [681.0, 1.0, 1.0, 316.54, 108.92, 13.975, 29.627],
 [682.0, 1.0, 1.0, 315.56, 108.73, 14.208, 29.487],
 [683.0, 1.0, 1.0, 314.58, 108.55, 14.441, 29.348],
 [684.0, 1.0, 1.0, 313.05, 108.59, 15.512, 29.348],
 [685.0, 1.0, 1.0, 311.51, 108.64, 16.584, 29.348],
 [686.0, 1.0, 1.0, 309.97, 108.69, 17.655, 29.348],
 [687.0, 1.0, 1.0, 308.43, 108.73, 18.727, 29.348],
 [688.0, 1.0, 1.

In [12]:
df_lstdf = pd.DataFrame(dfgt)

In [246]:
dfgt[0][1]

1.0

In [13]:
df_lstdf

0    1    2       3       4        5       6
0     669.0  1.0  1.0  323.67  111.57   13.043  29.581
1     670.0  1.0  1.0  323.06  111.53   13.649  29.581
2     671.0  1.0  1.0  322.46  111.48   14.255  29.581
3     672.0  1.0  1.0  321.85  111.43   14.860  29.581
4     673.0  1.0  1.0  321.25  111.39   15.466  29.581
..      ...  ...  ...     ...     ...      ...     ...
912  1109.0  8.0  3.0  184.75  205.07  136.080  53.297
913  1110.0  8.0  3.0  191.80  210.06  132.560  48.306
914  1111.0  8.0  3.0  199.82  215.34  129.040  43.022
915  1112.0  8.0  3.0  207.85  220.63  125.510  37.737
916  1113.0  8.0  3.0  215.87  225.91  121.990  32.453

[917 rows x 7 columns]

In [17]:
len(dfgt)

917

In [180]:
pwd

'C:\\Hazing\\haze-synthesis\\Hazed_data\\Cycle'

In [77]:
len(Usableframes_list_person)

589

In [11]:
Usableframes_list_person

['1.jpg',
 '2.jpg',
 '3.jpg',
 '4.jpg',
 '5.jpg',
 '6.jpg',
 '7.jpg',
 '8.jpg',
 '9.jpg',
 '10.jpg',
 '11.jpg',
 '12.jpg',
 '13.jpg',
 '14.jpg',
 '15.jpg',
 '16.jpg',
 '17.jpg',
 '18.jpg',
 '19.jpg',
 '20.jpg',
 '21.jpg',
 '22.jpg',
 '23.jpg',
 '24.jpg',
 '25.jpg',
 '26.jpg',
 '27.jpg',
 '28.jpg',
 '29.jpg',
 '30.jpg',
 '31.jpg',
 '32.jpg',
 '33.jpg',
 '34.jpg',
 '35.jpg',
 '36.jpg',
 '37.jpg',
 '38.jpg',
 '39.jpg',
 '40.jpg',
 '41.jpg',
 '42.jpg',
 '43.jpg',
 '44.jpg',
 '45.jpg',
 '46.jpg',
 '47.jpg',
 '48.jpg',
 '49.jpg',
 '50.jpg',
 '51.jpg',
 '52.jpg']

Car light haze GT generation

In [109]:
df_GT_car_light_haze=pd.read_csv('Cycle_generated_under_haze_GT.txt',
              sep='  ',
              names=["Frame_no","X","Y","W","H"])

C:\Users\Dr. Arun Khosla\AppData\Local\Temp\ipykernel_6944\1934321817.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_GT_car_light_haze=pd.read_csv('Cycle_generated_under_haze_GT.txt',


In [110]:
df_GT_car_light_haze

Frame_no          X       Y       W       H
0        58.0   -0.43126  96.797  20.584  36.973
1        59.0   -0.43126  96.797  25.814  36.973
2        60.0   -0.43126  96.797  27.423  61.916
3        61.0   -0.43126  96.797  31.849  61.916
4        62.0   -0.43126  96.797  34.665  61.916
..        ...        ...     ...     ...     ...
102     160.0  310.96000  97.384  25.671  61.572
103     161.0  313.46000  97.384  23.173  61.572
104     162.0  316.59000  97.384  20.049  61.572
105     163.0  320.65000  97.384  15.989  61.572
106     164.0  323.77000  97.384  12.866  61.572

[107 rows x 5 columns]

In [183]:
import shutil

In [205]:
List_framesUsable=[]

In [221]:
for j in Usableframes_list_person:
    print(lj)
    #shutil.copy2("Light_haze/0000"+j, "Frames_trackers_to_process/Light_haze")

In [ ]:
for j in range(0,107):
    shutil.copy2("Dense_haze/"+str_List_framesUsable[j], "Frames_trackers_to_process/Dense_haze")

In [218]:
str_List_framesUsable=[]

In [219]:
for i in List_framesUsable:
    str_List_framesUsable.append(str(i))

In [79]:
import os
list_prevnames=[]
for k in os.listdir("C:/Hazing/haze-synthesis/Hazed_data/Person/Frames_trackers_to_process/Light_haze"):
    list_prevnames.append(k)

In [80]:
list_postnames=[]
list_postnames=Usableframes_list_person


In [81]:
list_finalnames = zip(list_prevnames,list_postnames)

In [82]:
x_list=list(list_finalnames)

In [59]:
x_list

[('000058.jpg', '58.jpg'),
 ('000059.jpg', '59.jpg'),
 ('000060.jpg', '60.jpg'),
 ('000061.jpg', '61.jpg'),
 ('000062.jpg', '62.jpg'),
 ('000063.jpg', '63.jpg'),
 ('000064.jpg', '64.jpg'),
 ('000065.jpg', '65.jpg'),
 ('000066.jpg', '66.jpg'),
 ('000067.jpg', '67.jpg'),
 ('000068.jpg', '68.jpg'),
 ('000069.jpg', '69.jpg'),
 ('000070.jpg', '70.jpg'),
 ('000071.jpg', '71.jpg'),
 ('000072.jpg', '72.jpg'),
 ('000073.jpg', '73.jpg'),
 ('000074.jpg', '74.jpg'),
 ('000075.jpg', '75.jpg'),
 ('000076.jpg', '76.jpg'),
 ('000077.jpg', '77.jpg'),
 ('000078.jpg', '78.jpg'),
 ('000079.jpg', '79.jpg'),
 ('000080.jpg', '80.jpg'),
 ('000081.jpg', '81.jpg'),
 ('000082.jpg', '82.jpg'),
 ('000083.jpg', '83.jpg'),
 ('000084.jpg', '84.jpg'),
 ('000085.jpg', '85.jpg'),
 ('000086.jpg', '86.jpg'),
 ('000087.jpg', '87.jpg'),
 ('000088.jpg', '88.jpg'),
 ('000089.jpg', '89.jpg'),
 ('000090.jpg', '90.jpg'),
 ('000091.jpg', '91.jpg'),
 ('000092.jpg', '92.jpg'),
 ('000093.jpg', '93.jpg'),
 ('000094.jpg', '94.jpg'),
 

In [40]:
pwd

'C:\\Hazing\\haze-synthesis\\Hazed_data\\Car'

In [85]:
%cd C:/Hazing/haze-synthesis/Hazed_data/Person/Frames_trackers_to_process/Dense_haze

C:\Hazing\haze-synthesis\Hazed_data\Person\Frames_trackers_to_process\Dense_haze


In [86]:
import os
#for dirname in os.listdir("C:/Hazing/haze-synthesis/Hazed_data/Car/Frames_trackers_to_process/Light_haze"):
#if os.path.isdir(dirname):
for i, filename in x_list:
    os.rename(i,filename)
    #os.rename(dirname + "/" + filename, dirname + "/" + str(i) + ".bmp")

In [34]:
x_list[0][1]

'1.jpg'

Converting images to video

In [2]:
import cv2
import numpy as np
import glob

In [45]:
%cd C:\Hazing\haze-synthesis\Hazed_data\Person\Frames_trackers_to_process

C:\Hazing\haze-synthesis\Hazed_data\Person\Frames_trackers_to_process


In [46]:
import os
list_namesplitprev=[]
for k in os.listdir("C:/Hazing/haze-synthesis/Hazed_data/Person/Frames_trackers_to_process/Light_haze"):
    y=k.split(".jpg")
    list_namesplitprev.append(int(y[0]))
list_namesplitprev.sort()   

In [47]:
list_namesplitprev

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [48]:
list_namesplitpost=[]
for l in list_namesplitprev:
    list_namesplitpost.append(str(l)+".jpg")
    

In [49]:
for filename1 in list_namesplitpost:
    img1=cv2.imread("C:/Hazing/haze-synthesis/Hazed_data/Person/Frames_trackers_to_process/Light_haze/"+filename1)
    print(img1)

[[[175 182 199]
  [175 182 199]
  [175 182 199]
  ...
  [125 163 205]
  [125 163 205]
  [125 163 205]]

 [[176 183 200]
  [176 183 200]
  [177 184 201]
  ...
  [125 163 205]
  [125 163 205]
  [125 163 205]]

 [[175 182 201]
  [175 182 201]
  [176 183 202]
  ...
  [124 164 206]
  [124 164 206]
  [124 164 206]]

 ...

 [[230 225 222]
  [230 225 222]
  [230 225 222]
  ...
  [198 198 198]
  [199 199 199]
  [200 200 200]]

 [[230 225 224]
  [230 225 224]
  [230 225 224]
  ...
  [197 197 197]
  [198 198 198]
  [199 199 199]]

 [[230 225 224]
  [231 226 225]
  [231 226 225]
  ...
  [196 196 196]
  [195 195 195]
  [196 196 196]]]
[[[175 182 199]
  [176 183 200]
  [176 183 200]
  ...
  [124 165 204]
  [126 165 204]
  [126 165 204]]

 [[177 184 201]
  [178 185 202]
  [178 185 202]
  ...
  [124 165 204]
  [126 165 204]
  [126 165 204]]

 [[177 185 202]
  [177 185 202]
  [177 185 202]
  ...
  [122 164 206]
  [124 165 204]
  [124 165 204]]

 ...

 [[230 225 222]
  [230 225 222]
  [230 225 222]
  ..

In [108]:
%cd C:\Hazing\haze-synthesis\PICS\Trackers_Output\Sort+Yv7\Cycle

C:\Hazing\haze-synthesis\PICS\Trackers_Output\Sort+Yv7\Cycle


In [52]:
img_array=[]
for filename in list_namesplitpost:
    img=cv2.imread("C:/Hazing/haze-synthesis/Hazed_data/Person/Frames_trackers_to_process/dense_haze/"+filename)
    height, width, layers=img.shape
    size=(width,height)
    img_array.append(img)
    print(filename)
    
out=cv2.VideoWriter('Cycle_dense_haze_video.avi',cv2.VideoWriter_fourcc(*'DIVX'),25,size)

for i in range(len(img_array)):
    out.write(img_array[i])
out.release()

1.jpg
2.jpg
3.jpg
4.jpg
5.jpg
6.jpg
7.jpg
8.jpg
9.jpg
10.jpg
11.jpg
12.jpg
13.jpg
14.jpg
15.jpg
16.jpg
17.jpg
18.jpg
19.jpg
20.jpg
21.jpg
22.jpg
23.jpg
24.jpg
25.jpg
26.jpg
27.jpg
28.jpg
29.jpg
30.jpg
31.jpg
32.jpg
33.jpg
34.jpg
35.jpg
36.jpg
37.jpg
38.jpg
39.jpg
40.jpg
41.jpg
42.jpg
43.jpg
44.jpg
45.jpg
46.jpg
47.jpg
48.jpg
49.jpg
50.jpg
51.jpg
52.jpg
53.jpg
54.jpg
55.jpg
56.jpg
57.jpg
58.jpg
59.jpg
60.jpg
61.jpg
62.jpg
63.jpg
64.jpg
65.jpg
66.jpg
67.jpg
68.jpg
69.jpg
70.jpg
71.jpg
72.jpg
73.jpg
74.jpg
75.jpg
76.jpg
77.jpg
78.jpg
79.jpg
80.jpg
81.jpg
82.jpg
83.jpg
84.jpg
85.jpg
86.jpg
87.jpg
88.jpg
89.jpg
90.jpg
91.jpg
92.jpg
93.jpg
94.jpg
95.jpg
96.jpg
97.jpg
98.jpg
99.jpg
100.jpg
101.jpg
102.jpg
103.jpg
104.jpg
105.jpg
106.jpg
107.jpg
108.jpg
109.jpg
110.jpg
111.jpg
112.jpg
113.jpg
114.jpg
115.jpg
116.jpg
117.jpg
118.jpg
119.jpg
120.jpg
121.jpg
122.jpg
123.jpg
124.jpg
125.jpg
126.jpg
127.jpg
128.jpg
129.jpg
130.jpg
131.jpg
132.jpg
133.jpg
134.jpg
135.jpg
136.jpg
137.jpg
138.jpg
139.

In [5]:
print(img_array)

[array([[[124, 125, 129],
        [126, 127, 131],
        [128, 129, 133],
        ...,
        [ 74,  67,  52],
        [ 78,  71,  56],
        [ 78,  71,  56]],

       [[135, 134, 136],
        [134, 136, 137],
        [138, 137, 139],
        ...,
        [ 71,  64,  49],
        [ 75,  68,  53],
        [ 76,  69,  54]],

       [[139, 137, 136],
        [136, 137, 135],
        [138, 136, 135],
        ...,
        [ 67,  60,  45],
        [ 70,  65,  50],
        [ 73,  68,  53]],

       ...,

       [[209, 209, 209],
        [209, 209, 209],
        [210, 210, 210],
        ...,
        [199, 199, 199],
        [201, 200, 202],
        [208, 207, 209]],

       [[210, 210, 210],
        [209, 209, 209],
        [209, 209, 209],
        ...,
        [199, 199, 199],
        [201, 201, 201],
        [208, 208, 208]],

       [[209, 209, 209],
        [209, 209, 209],
        [209, 209, 209],
        ...,
        [200, 200, 200],
        [202, 202, 202],
        [208, 208, 208]

In [38]:
df_car_light_haze

Frame_no    X    Y    W   H
0          1   16  103   69  52
1          2   19  105   69  53
2          3   22  106   70  53
3          4   25  107   70  54
4          5   27  108   70  54
5          6   30  110   71  55
6          7   33  111   72  56
7          8   36  113   73  57
8          9   39  115   74  57
9         10   41  116   74  58
10        11   44  118   75  59
11        12   47  120   76  60
12        13   50  121   77  61
13        14   53  123   78  61
14        15   55  124   79  62
15        16   58  126   80  63
16        17   61  128   81  64
17        18   64  129   81  64
18        19   67  131   83  65
19        20   71  133   84  67
20        21   74  135   85  68
21        22   78  137   87  69
22        23   81  139   88  70
23        24   85  141   89  71
24        25   88  143   90  72
25        26   92  145   92  73
26        27   95  147   93  74
27        28   99  149   94  75
28        29  102  151   96  76
29        30  106  153   97  77
30        31  110  155   99  79
31        32  114  158  101  81
32        33  118  160  104  83
33        34  122  162  106  84
34        35  126  165  108  86
35        36  130  167  110  88
36        37  136  170  112  85
37        38  139  172  115  86
38        39  145  175  118  86
39        40  150  178  119  82
40        41  155  181  120  78
41        42  161  184  121  75
42        43  166  187  122  71
43        44  171  190  123  67
44        45  177  193  124  63
45        46  182  196  125  60
46        47  189  200  122  56
47        48  195  204  120  52
48        49  201  208  118  49
49        50  208  212  115  45
50        51  214  216  113  41
51        52  221  219  111  38

In [214]:
%cd Person

C:\Hazing\haze-synthesis\PICS\Trackers_Output\Sort+Yv7\Person


In [48]:
#Car_lighthaze_yoloDeepsort.txt

In [240]:
df_GenYOLOSsort_carlight=pd.read_csv('TXT1_person_densehaze_SORTv7.txt',
              sep='  ',
              names=["X","Y","W","H"])

C:\Users\Dr. Arun Khosla\AppData\Local\Temp\ipykernel_6944\95760908.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_GenYOLOSsort_carlight=pd.read_csv('TXT1_person_densehaze_SORTv7.txt',


In [241]:
df_GenYOLOSsort_carlight

X      Y      W      H
0    112.0   69.0  182.0  241.0
1    113.0   69.0  182.0  253.0
2    115.0   68.0  183.0  251.0
3    116.0   67.0  183.0  251.0
4    118.0   67.0  184.0  242.0
..     ...    ...    ...    ...
638  322.0  123.0  336.0  153.0
639   86.0  100.0   95.0  124.0
640  323.0  124.0  336.0  152.0
641   87.0   97.0   96.0  124.0
642  322.0  123.0  336.0  152.0

[643 rows x 4 columns]

In [95]:
df_GenYOLOSsort_carlight=df_GenYOLOSsort_carlight.iloc[:,[2,3,4,5]]

In [96]:
df_GenYOLOSsort_carlight

X    Y    W   H
0    22  106   68  52
1    25  108   68  51
2    27  109   69  52
3    30  110   69  54
4    33  112   70  53
5    35  114   71  54
6    38  114   72  56
7    40  116   74  56
8    43  118   74  56
9    45  120   76  57
10   48  120   78  59
11   52  123   75  58
12   54  124   78  59
13   57  126   80  61
14   61  128   79  61
15   63  129   80  63
16   66  130   82  65
17   70  133   83  65
18   73  135   84  65
19   76  136   85  67
20   81  139   85  67
21   84  141   86  68
22   87  143   88  69
23   90  145   90  70
24   94  147   91  71
25   97  149   94  73
26  101  152   95  73
27  107  154   94  76
28  109  155   98  79
29  113  157  101  80
30  117  160  102  80
31  123  163  102  82
32  127  165  105  85
33  131  167  109  85
34  135  169  112  86
35  145  175  116  80
36  150  179  120  76
37    0   85   31  38
38    0   87   32  37
39    0   93   35  33
40    0   89   36  38
41    1   92   37  38
42    0   93   41  38
43    5  102   38  32
44    6  100   40  33

In [97]:
df_GenYOLOSsort_carlight['W']=df_GenYOLOSsort_carlight['X']+df_GenYOLOSsort_carlight['W']
df_GenYOLOSsort_carlight['H']=df_GenYOLOSsort_carlight['Y']+df_GenYOLOSsort_carlight['H']

C:\Users\Acer\AppData\Local\Temp/ipykernel_12332/345912511.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_GenYOLOSsort_carlight['W']=df_GenYOLOSsort_carlight['X']+df_GenYOLOSsort_carlight['W']
C:\Users\Acer\AppData\Local\Temp/ipykernel_12332/345912511.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_GenYOLOSsort_carlight['H']=df_GenYOLOSsort_carlight['Y']+df_GenYOLOSsort_carlight['H']


In [9]:
pwd

'C:\\Hazing\\haze-synthesis\\PICS\\Trackers_Output\\Sort+Yv7\\Car'

In [98]:
df_GenYOLOSsort_carlight

X    Y    W    H
0    22  106   90  158
1    25  108   93  159
2    27  109   96  161
3    30  110   99  164
4    33  112  103  165
5    35  114  106  168
6    38  114  110  170
7    40  116  114  172
8    43  118  117  174
9    45  120  121  177
10   48  120  126  179
11   52  123  127  181
12   54  124  132  183
13   57  126  137  187
14   61  128  140  189
15   63  129  143  192
16   66  130  148  195
17   70  133  153  198
18   73  135  157  200
19   76  136  161  203
20   81  139  166  206
21   84  141  170  209
22   87  143  175  212
23   90  145  180  215
24   94  147  185  218
25   97  149  191  222
26  101  152  196  225
27  107  154  201  230
28  109  155  207  234
29  113  157  214  237
30  117  160  219  240
31  123  163  225  245
32  127  165  232  250
33  131  167  240  252
34  135  169  247  255
35  145  175  261  255
36  150  179  270  255
37    0   85   31  123
38    0   87   32  124
39    0   93   35  126
40    0   89   36  127
41    1   92   38  130
42    0   93   41  131
43    5  102   43  134
44    6  100   46  133

In [242]:
List_GenYOLOSsort_carlight=df_GenYOLOSsort_carlight.to_numpy().tolist()

In [243]:
GT_YOLOSsort_carlight=pd.read_csv('Person_generated_under_haze_GT.txt',
                                 sep='  ',
                                 names=["Frame_no","X","Y","W","H"])

C:\Users\Dr. Arun Khosla\AppData\Local\Temp\ipykernel_6944\889514048.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  GT_YOLOSsort_carlight=pd.read_csv('Person_generated_under_haze_GT.txt',


In [244]:
GT_YOLOSsort_carlight=GT_YOLOSsort_carlight.iloc[:,[1,2,3,4]]

In [245]:
GT_YOLOSsort_carlight ## YOLOSsort=YOLOStrongSort

X        Y       W       H
0    106.76   69.233  75.730  185.21
1    107.79   69.233  74.701  183.82
2    108.82   69.233  73.672  182.43
3    109.85   69.233  72.643  181.04
4    110.88   69.233  71.614  179.65
..      ...      ...     ...     ...
584  320.37  121.300  14.611   31.28
585  321.09  121.350  14.354   31.28
586  321.81  121.400  14.096   31.28
587  322.53  121.450  13.839   31.28
588  323.25  121.500  13.582   31.28

[589 rows x 4 columns]

In [246]:
GT_YOLOSsort_carlight['W']=GT_YOLOSsort_carlight['X']+GT_YOLOSsort_carlight['W']
GT_YOLOSsort_carlight['H']=GT_YOLOSsort_carlight['Y']+GT_YOLOSsort_carlight['H']

In [247]:
List_GT_YOLOSsort_carlight=GT_YOLOSsort_carlight.to_numpy().tolist()  

In [248]:
List_GT_YOLOSsort_carlight

[[106.76, 69.233, 182.49, 254.443],
 [107.79, 69.233, 182.49099999999999, 253.053],
 [108.82, 69.233, 182.492, 251.663],
 [109.85, 69.233, 182.493, 250.273],
 [110.88, 69.233, 182.494, 248.883],
 [111.91, 69.233, 182.495, 247.493],
 [112.94, 69.233, 182.49599999999998, 246.103],
 [113.97, 69.233, 182.497, 244.723],
 [115.0, 69.233, 182.498, 243.333],
 [116.02, 69.233, 182.48899999999998, 241.943],
 [117.05, 69.233, 182.49099999999999, 240.553],
 [118.08, 69.233, 182.49200000000002, 239.163],
 [119.11, 69.233, 182.493, 237.773],
 [120.14, 69.233, 182.494, 236.383],
 [121.17, 69.233, 182.495, 234.993],
 [122.2, 69.233, 182.496, 233.603],
 [123.23, 69.233, 182.497, 232.213],
 [122.85, 69.816, 182.117, 231.186],
 [122.47, 70.399, 181.737, 230.159],
 [122.09, 70.982, 181.357, 229.132],
 [121.72, 71.565, 180.987, 228.105],
 [121.34, 72.148, 180.607, 227.06799999999998],
 [120.96, 72.732, 180.227, 226.042],
 [120.59, 73.315, 179.857, 225.015],
 [120.21, 73.898, 179.477, 223.988],
 [119.83, 74

In [251]:
import math
car_rste_light_haze=[]
for i in range(0,len(List_GT_YOLOSsort_carlight)):
    rootsquare=math.sqrt(((List_GT_YOLOSsort_carlight[i][0]-List_GenYOLOSsort_carlight[i][0])**2)+((List_GT_YOLOSsort_carlight[i][1]-List_GenYOLOSsort_carlight[i][1])**2))
    car_rste_light_haze.append(rootsquare)

In [252]:
car_rste_light_haze

[5.245177690031096,
 5.215207474300513,
 6.301800457012273,
 6.542842577962586,
 7.461949410174267,
 6.213564918788573,
 5.065361685013225,
 4.102339454506416,
 2.6687616978666315,
 3.4024533795483505,
 5.150416390933841,
 3.8777169829681966,
 4.21454493391635,
 7.7682616459539995,
 7.811221991468424,
 2.7742186287313366,
 5.896710014915094,
 3.295505424058649,
 2.943484499704388,
 4.560748184234691,
 5.897255717704634,
 9.378779451506473,
 9.049277540223855,
 4.9474564171905575,
 4.276739879861764,
 1.9021727050927841,
 1.0385547650461269,
 6.444145327349464,
 0.3780211634287161,
 0.3706332418982339,
 3.7566495710939023,
 1.1078542322887102,
 1.8622416599356837,
 3.0654730466927895,
 4.522342755696429,
 7.439914045202409,
 5.913851198669105,
 3.9839087589953706,
 4.335276346439751,
 5.018090872034907,
 2.8824345612693465,
 1.0456404735854496,
 6.923750500992942,
 6.100208275132906,
 7.326274906117026,
 4.97809762861276,
 2.4129494400007645,
 3.6411686310853555,
 4.157413137998199,
 4.

## Accuracy measures for all algorithms

In [253]:
## code for complete IOU
import cv2
def IOU(box1, box2):
    """ assumption:
         box1 = [x1,y1,x2,y2], and box2 = [x3,y3,x4,y4],
        (x1,y1) and (x3,y3) represent the top left coordinate,
        and (x2,y2) and (x4,y4) represent the bottom right coordinate """
    x1, y1, x2, y2 = box1
    x3, y3, x4, y4 = box2
    x_inter1 = max(x1, x3)
    y_inter1 = max(y1, y3)
    x_inter2 = min(x2, x4)
    y_inter2 = min(y2, y4)
    width_inter = abs(x_inter2 - x_inter1)
    height_inter = abs(y_inter2 - y_inter1)
    area_inter = width_inter * height_inter
    width_box1 = abs(x2 - x1)
    height_box1 = abs(y2 - y1)
    width_box2 = abs(x4 - x3)
    height_box2 = abs(y4 - y3)
    area_box1 = width_box1 * height_box1
    area_box2 = width_box2 * height_box2
    area_union = area_box1 + area_box2 - area_inter
    iou = area_inter / area_union
    return iou

In [254]:
def PRC(box1, box2):
    """ assumption:
         box1 = [x1,y1,x2,y2], and box2 = [x3,y3,x4,y4],
        (x1,y1) and (x3,y3) represent the top left coordinate,
        and (x2,y2) and (x4,y4) represent the bottom right coordinate """
    x1, y1, x2, y2 = box1
    x3, y3, x4, y4 = box2
    x_inter1 = max(x1, x3)
    y_inter1 = max(y1, y3)
    x_inter2 = min(x2, x4)
    y_inter2 = min(y2, y4)
    width_inter = abs(x_inter2 - x_inter1)
    height_inter = abs(y_inter2 - y_inter1)
    area_inter = width_inter * height_inter
    width_box1 = abs(x2 - x1)
    height_box1 = abs(y2 - y1)
    width_box2 = abs(x4 - x3)
    height_box2 = abs(y4 - y3)
    area_box1 = width_box1 * height_box1
    area_box2 = width_box2 * height_box2
    if area_box2==0:
        prec=0
    else:
        prec=area_inter/area_box2
    #area_union = area_box1 + area_box2 - area_inter
    #iou = area_inter / area_union
    return prec

In [255]:
def REC(box1, box2):
    """ assumption:
         box1 = [x1,y1,x2,y2], and box2 = [x3,y3,x4,y4],
        (x1,y1) and (x3,y3) represent the top left coordinate,
        and (x2,y2) and (x4,y4) represent the bottom right coordinate """
    x1, y1, x2, y2 = box1
    x3, y3, x4, y4 = box2
    x_inter1 = max(x1, x3)
    y_inter1 = max(y1, y3)
    x_inter2 = min(x2, x4)
    y_inter2 = min(y2, y4)
    width_inter = abs(x_inter2 - x_inter1)
    height_inter = abs(y_inter2 - y_inter1)
    area_inter = width_inter * height_inter
    width_box1 = abs(x2 - x1)
    height_box1 = abs(y2 - y1)
    width_box2 = abs(x4 - x3)
    height_box2 = abs(y4 - y3)
    area_box1 = width_box1 * height_box1
    area_box2 = width_box2 * height_box2
    rec=area_inter/area_box1
    #area_union = area_box1 + area_box2 - area_inter
    #iou = area_inter / area_union
    return rec

In [256]:
def FMEA(prci, reca):
    fmeas=((2*prci*reca)/(prci+reca))
    return fmeas

In [257]:
# List_GenYOLOSsort_carlight
# List_GT_YOLOSsort_carlight

In [258]:
car_IOU_light_haze=[]
for m in range(0,len(List_GT_YOLOSsort_carlight)):
    iou=IOU(List_GT_YOLOSsort_carlight[m],List_GenYOLOSsort_carlight[m])
    car_IOU_light_haze.append(iou)

In [259]:
car_IOU_light_haze

[0.8562501459433537,
 0.9223362136647352,
 0.9009745936534798,
 0.8955835182595616,
 0.8394799923773972,
 0.876837190122901,
 0.8690155565893637,
 0.8805890428956784,
 0.9363357716848257,
 0.9071980000190955,
 0.9195295321239227,
 0.9555581668914074,
 0.9242897931022511,
 0.9147174297779623,
 0.9064477624422079,
 0.9534103050008708,
 0.9016632791252108,
 0.8747851311246391,
 0.8520102663729998,
 0.8195944335930226,
 0.8181019415755282,
 0.7702739160151463,
 0.7635891090043253,
 0.8498091800376796,
 0.854033196346288,
 0.8618746384421078,
 0.874015968609773,
 0.81607599574919,
 0.8647481339476984,
 0.8600533690817183,
 0.8110765769791328,
 0.8470435336127735,
 0.8216863475182532,
 0.8131068801237308,
 0.8046456351051863,
 0.7911817283757013,
 0.8128785230803058,
 0.8444032052044991,
 0.8165542715369525,
 0.8450972850495383,
 0.8693439318535854,
 0.9012523857774118,
 0.8704271919997061,
 0.8736798973340323,
 0.8577483480520564,
 0.8558893521084541,
 0.8597225102759064,
 0.836835426437506

In [260]:
car_PREC_light_haze=[]
for m in range(0,len(List_GT_YOLOSsort_carlight)):
    prc=PRC(List_GT_YOLOSsort_carlight[m],List_GenYOLOSsort_carlight[m])
    car_PREC_light_haze.append(prc)

In [261]:
car_REC_light_haze=[]
for m in range(0,len(List_GT_YOLOSsort_carlight)):
    reca=REC(List_GT_YOLOSsort_carlight[m],List_GenYOLOSsort_carlight[m])
    car_REC_light_haze.append(reca)

In [262]:
## f-measure
car_FMEAS_light_haze=[]    
for m in range(0,len(List_GT_YOLOSsort_carlight)):
    fmeas=FMEA(car_PREC_light_haze[m],car_REC_light_haze[m])
    car_FMEAS_light_haze.append(fmeas)

In [263]:
car_FMEAS_light_haze

[0.9225590072702232,
 0.9595992700011583,
 0.9479080853173301,
 0.9449159160044244,
 0.9127362035532977,
 0.9343774673023002,
 0.9299179490781442,
 0.9365034282447718,
 0.9671212868934507,
 0.9513411822055311,
 0.9580780256154547,
 0.9772740929617868,
 0.9606555066866035,
 0.9554594485349585,
 0.9509285072474531,
 0.9761495601411253,
 0.9482890993614677,
 0.9332110828080616,
 0.9200923794462409,
 0.9008539688425274,
 0.8999516725300657,
 0.8702313343112671,
 0.8659489958354609,
 0.9188073983072886,
 0.9212706633617098,
 0.9258138229577765,
 0.9327732348600597,
 0.8987245001413416,
 0.9274690969841748,
 0.9247620346574403,
 0.8956844644658866,
 0.9171884887368912,
 0.9021161613662694,
 0.8969210685122351,
 0.8917491827233841,
 0.8834187127323694,
 0.8967821205130988,
 0.9156384057691718,
 0.8990144520659777,
 0.9160463157115845,
 0.9301059233028028,
 0.948061806543264,
 0.9307255537373975,
 0.9325818124826433,
 0.923427921711193,
 0.9223495475482827,
 0.9245707416300067,
 0.911170826077

In [101]:
AVG_car_PREC_light_haze=sum(car_PREC_light_haze)/len(car_rste_light_haze)   #Avg precision
AVG_car_REC_light_haze=sum(car_REC_light_haze)/len(car_rste_light_haze)     #Avg recall
AVG_car_FMEAS_light_haze=sum(car_FMEAS_light_haze)/len(car_rste_light_haze) #Avg FMeasure

print("Avg Precision LightHaze Car Sort+YOLOv7 RGB is: ", AVG_car_PREC_light_haze)
print("Avg Recall LightHaze Car Sort+YOLOv7 RGB is: ", AVG_car_REC_light_haze)
print("Avg FMeasure LightHaze Car Sort+YOLOv7 RGB is: ", AVG_car_FMEAS_light_haze)

Avg Precision LightHaze Car Sort+YOLOv7 RGB is:  3.0352755460777376
Avg Recall LightHaze Car Sort+YOLOv7 RGB is:  1.1426786440639853
Avg FMeasure LightHaze Car Sort+YOLOv7 RGB is:  1.4112697846266864


In [73]:
AVG_car_PREC_light_haze=sum(car_PREC_light_haze)/len(car_rste_light_haze)   #Avg precision
AVG_car_REC_light_haze=sum(car_REC_light_haze)/len(car_rste_light_haze)     #Avg recall
AVG_car_FMEAS_light_haze=sum(car_FMEAS_light_haze)/len(car_rste_light_haze) #Avg FMeasure

print("Avg Precision DenseHaze Car Sort+YOLOv7 RGB is: ", AVG_car_PREC_light_haze)
print("Avg Recall DenseHaze Car Sort+YOLOv7 RGB is: ", AVG_car_REC_light_haze)
print("Avg FMeasure DenseHaze Car Sort+YOLOv7 RGB is: ", AVG_car_FMEAS_light_haze)

Avg Precision DenseHaze Car Sort+YOLOv7 RGB is:  1.3048638282304486
Avg Recall DenseHaze Car Sort+YOLOv7 RGB is:  0.7876473186889515
Avg FMeasure DenseHaze Car Sort+YOLOv7 RGB is:  0.870295553776324


In [179]:
AVG_car_PREC_light_haze=sum(car_PREC_light_haze)/len(car_rste_light_haze)   #Avg precision
AVG_car_REC_light_haze=sum(car_REC_light_haze)/len(car_rste_light_haze)     #Avg recall
AVG_car_FMEAS_light_haze=sum(car_FMEAS_light_haze)/len(car_rste_light_haze) #Avg FMeasure

print("Avg Precision denseHaze Cycle Sort+YOLOv7 RGB is: ", AVG_car_PREC_light_haze)
print("Avg Recall denseHaze Cycle Sort+YOLOv7 RGB is: ", AVG_car_REC_light_haze)
print("Avg FMeasure denseHaze Cycle Sort+YOLOv7 RGB is: ", AVG_car_FMEAS_light_haze)

Avg Precision denseHaze Cycle Sort+YOLOv7 RGB is:  0.32372395361027034
Avg Recall denseHaze Cycle Sort+YOLOv7 RGB is:  0.3187999820201007
Avg FMeasure denseHaze Cycle Sort+YOLOv7 RGB is:  0.3178416161272738


In [205]:
AVG_car_PREC_light_haze=sum(car_PREC_light_haze)/len(car_rste_light_haze)   #Avg precision
AVG_car_REC_light_haze=sum(car_REC_light_haze)/len(car_rste_light_haze)     #Avg recall
AVG_car_FMEAS_light_haze=sum(car_FMEAS_light_haze)/len(car_rste_light_haze) #Avg FMeasure

print("Avg Precision lightHaze Cycle Sort+YOLOv7 RGB is: ", AVG_car_PREC_light_haze)
print("Avg Recall lightHaze Cycle Sort+YOLOv7 RGB is: ", AVG_car_REC_light_haze)
print("Avg FMeasure lightHaze Cycle Sort+YOLOv7 RGB is: ", AVG_car_FMEAS_light_haze)

Avg Precision lightHaze Cycle Sort+YOLOv7 RGB is:  0.7869646403068867
Avg Recall lightHaze Cycle Sort+YOLOv7 RGB is:  0.5827343862169797
Avg FMeasure lightHaze Cycle Sort+YOLOv7 RGB is:  0.6397880373998635


In [235]:
AVG_car_PREC_light_haze=sum(car_PREC_light_haze)/len(car_rste_light_haze)   #Avg precision
AVG_car_REC_light_haze=sum(car_REC_light_haze)/len(car_rste_light_haze)     #Avg recall
AVG_car_FMEAS_light_haze=sum(car_FMEAS_light_haze)/len(car_rste_light_haze) #Avg FMeasure

print("Avg Precision lightHaze Person Sort+YOLOv7 RGB is: ", AVG_car_PREC_light_haze)
print("Avg Recall lightHaze Person Sort+YOLOv7 RGB is: ", AVG_car_REC_light_haze)
print("Avg FMeasure lightHaze Person Sort+YOLOv7 RGB is: ", AVG_car_FMEAS_light_haze)

Avg Precision lightHaze Person Sort+YOLOv7 RGB is:  19.92042041947028
Avg Recall lightHaze Person Sort+YOLOv7 RGB is:  1.1576310848065818
Avg FMeasure lightHaze Person Sort+YOLOv7 RGB is:  1.491201246454819


In [264]:
AVG_car_PREC_light_haze=sum(car_PREC_light_haze)/len(car_rste_light_haze)   #Avg precision
AVG_car_REC_light_haze=sum(car_REC_light_haze)/len(car_rste_light_haze)     #Avg recall
AVG_car_FMEAS_light_haze=sum(car_FMEAS_light_haze)/len(car_rste_light_haze) #Avg FMeasure

print("Avg Precision denseHaze Person Sort+YOLOv7 RGB is: ", AVG_car_PREC_light_haze)
print("Avg Recall denseHaze Person Sort+YOLOv7 RGB is: ", AVG_car_REC_light_haze)
print("Avg FMeasure denseHaze Person Sort+YOLOv7 RGB is: ", AVG_car_FMEAS_light_haze)

Avg Precision denseHaze Person Sort+YOLOv7 RGB is:  0.9769040536217849
Avg Recall denseHaze Person Sort+YOLOv7 RGB is:  0.7768382127351131
Avg FMeasure denseHaze Person Sort+YOLOv7 RGB is:  0.8523917831169884


In [265]:
data_metrics_YOloSS_Carlight= pd.DataFrame(list(zip(car_rste_light_haze,car_IOU_light_haze,car_PREC_light_haze,car_REC_light_haze,car_FMEAS_light_haze)), columns =['rste_car_light', 'IOU_car_light','PREC_car_light','REC_car_light','FMEAS_car_light']) 

In [266]:
data_metrics_YOloSS_Carlight ## YOloSS = YOLOStrongSort

rste_car_light  IOU_car_light  PREC_car_light  REC_car_light  \
0          5.245178       0.856250        0.998645       0.857246   
1          5.215207       0.922336        0.998734       0.923416   
2          6.301800       0.900975        0.985842       0.912785   
3          6.542843       0.895584        0.976468       0.915339   
4          7.461949       0.839480        0.964713       0.866074   
..              ...            ...             ...            ...   
584       29.683108       1.080713        1.090022       0.992160   
585      275.353683       1.041025        1.426086       0.794047   
586       31.686213       1.215619        1.080343       1.114834   
587      276.796646       1.292592        1.540074       0.889427   
588       32.346754       1.964849        1.361352       1.291353   

     FMEAS_car_light  
0           0.922559  
1           0.959599  
2           0.947908  
3           0.944916  
4           0.912736  
..               ...  
584         1.038791  
585         1.020100  
586         1.097318  
587         1.127625  
588         1.325429  

[589 rows x 5 columns]

In [238]:
list_data_metrics_YOloSS_Carlight=data_metrics_YOloSS_Carlight.to_numpy().tolist()

In [267]:
with open('Person_DataMetrics_densehaze_SORT+YOLOv7.txt', 'a') as f:
    for i in range(0,len(list_data_metrics_YOloSS_Carlight)):
             f.write(str(list_data_metrics_YOloSS_Carlight[i][0])+"  "+str(list_data_metrics_YOloSS_Carlight[i][1])+"  "+str(list_data_metrics_YOloSS_Carlight[i][2])+"  "+str(list_data_metrics_YOloSS_Carlight[i][3])+"  "+str(list_data_metrics_YOloSS_Carlight[i][4])+ '\n')